# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Committee on Coherence at Scale
email:
description: > # The Committee on Coherence at Scale, sponsored by CLIR, analyzes emerging national-scale digital projects and their potential to help transform higher education in terms of scholarly productivity, teaching, cost-efficiency, and sustainability.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://coherence.clir.org/" # the base hostname & protocol for your site
twitter_username: clirdlf
github_username:  clirdlf

google-tracking-id: UA-9461551-2

exclude: ['.gitignore', '.env', '.git', 'node_modules']
sass:
  style: compressed

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
  - jekyll-feed
